config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: :destroy do
    member do
      post :vote
    end
    resources :comments, only: :create do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:create, :new, :show]
  resources :users, only: [:create, :edit, :show, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true, length: {minimum: 3}
  validates :user_id, presence: true
  validates :post_id, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = session[:user_id]
    @comment_limit = 5

    if @comment.save
      flash[:notice] = "You're comment was successfully created."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    respond_to do |format|
      @comment.process_vote(params[:vote], session[:user_id])
      format.html { redirect_to :back; flash[:notice] = @post.html_message }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit!
  end
end

app/views/comments/_comment.html.erb
<div class='row'>
  <div class='span1 well text-center vote_arrows'>
    <% if logged_in? %>  
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up <%= voted_true?(comment) %>" id="comment_<%= comment.id %>_arrow"></i>
      <% end %>
      <br>
    <% end %>
    <span id="comment_<%= comment.id %>_votes"><%= "#{comment.vote_total} votes" %></span>
    <br>
    <% if logged_in? %>  
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down <%= voted_false?(comment) %>" id="comment_<%= comment.id %>_arrow"></i>
      <% end %>
    <% end %>
  </div>

  <div class='span8 well'>
    <p>
      <em>"<%= comment.body %>"</em>
      <% if profile_page %>
        on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </p>
    <p>
      <small><span class='quiet'>Posted by:</span> <%= link_to comment.creator.username, user_path(comment.creator) %> - <%= format_time(comment.created_at) %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").fadeOut(200, function() {
  $("#comment_<%= @comment.id %>_votes").hide().html("<%= @comment.js_message %>").fadeIn(200, function () {
    $("#comment_<%= @comment.id %>_votes").delay(1000).fadeOut(200, function () {      
      $("#comment_<%= @comment.id %>_votes").hide().html("<%= @comment.vote_total %> votes").fadeIn({duration: 200, queue: false});
    });
  });
});

$('#comment_<%= @comment.id %>_arrow<%= @comment.fade_out %>').fadeOut({duration: 200, queue: false});

$('#comment_<%= @comment.id %>_arrow<%= @comment.fade_in %>').removeClass('collapse').hide().delay(200).fadeIn(200);