config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: :destroy do
    member do
      post :vote
    end
    resources :comments, only: :create do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:create, :new, :show]
  resources :users, only: [:create, :edit, :show, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Slugable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
 

  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 3}
  validates :url, presence: true

  slugable_column :title
  
end

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if error_object.errors.any? %>
  <div class='alert alert-error'>
    <strong>Please correct the following errors:</strong>
    <ul>
      <% error_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= render 'shared/errors', error_object: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <br/>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
    <br/>
    <%= f.label :url, "URL" %>
    <%= f.text_field :url %>
    <br/>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    <br/>
    <br/>
    <%= f.submit submit_button_text, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shared/_pagination.html.erb
<div class="row" id="paginate_group">
  <div class="span10">
    <div class="btn-group">
      <% if @page == 0 %>
        <button class="btn disabled">
          <i class="icon-chevron-left"></i>
        </button>
      <% else %>
        <%= link_to polymorphic_path(link_type, page: @page - 1), class: "btn", remote: true do %>
          <i class="icon-chevron-left"></i>
        <% end %> 
      <% end %>
      <button class="btn">Page <%= @last_page == 0 ? 0 : @page + 1 %>/<%= @last_page %></button>
      <% if @page >= @last_page - 1 %>
        <button class="btn disabled">
          <i class="icon-chevron-right"></i>
        </button>
      <% else %>
        <%= link_to polymorphic_path(link_type, page: @page + 1), class: "btn", remote: true do %>
          <i class="icon-chevron-right"></i>
        <% end %> 
      <% end %> 
    </div>
  </div>
  <br>
  <br>
</div>