config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: :destroy do
    member do
      post :vote
    end
    resources :comments, only: :create do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:create, :new, :show]
  resources :users, only: [:create, :edit, :show, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Slugable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
 

  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 3}
  validates :url, presence: true

  slugable_column :title
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_login, only: [:new, :create, :vote]
  before_action :require_post_creator, only: [:edit, :update]

  def index
    @page = params[:page].to_i if params[:page] || 0
    @last_page = (Post.all.size / POSTS_PER_PAGE.to_f).ceil
    @posts = Post.limit(POSTS_PER_PAGE).offset(@page * POSTS_PER_PAGE)
    respond_to(:html, :js)
  end

  def show
    @comment = Comment.new
    @limit_increase = params[:limit].to_i if params[:limit] || 0
    @comment_limit = 5 + @limit_increase
    respond_to(:html, :js)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      flash[:notice] = "Your post was saved."
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:notice] = "Your post was updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    respond_to do |format|
      @post.process_vote(params[:vote], session[:user_id])
      format.html { redirect_to :back; flash[:notice] = @post.html_message }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :url, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_post_creator
    access_denied unless logged_in? && current_user == @post.creator || admin?
  end
end

app/views/posts/_post.html.erb
<div class="row paginate_group">
  <div class='span1 well text-center vote_arrows'>
    <% if logged_in? %>  
      <%= link_to vote_post_path(post, vote: true), method: :post, remote: true do %>
        <i class="icon-arrow-up <%= voted_true?(post) %>" id="post_<%= post.slug %>_arrow"></i>
      <% end %>
      <br>
    <% end %>
    <span id="post_<%= post.slug %>_votes"><%= "#{post.vote_total} votes" %></span>
    <br>
    <% if logged_in? %>  
      <%= link_to vote_post_path(post, vote: false), method: :post, remote: true do %>
        <i class="icon-arrow-down <%= voted_false?(post) %>" id="post_<%= post.slug %>_arrow"></i>
      <% end %>
    <% end %>
  </div>

  <div class='span8 well'>
    <%= render post.categories %>
    <br>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>Posted by: </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small> - <%= format_full_time(post.created_at) %></small>
    </p>
    <p>
      <small><%= link_to "#{post.comments.size} comments", post_path(post) %></small>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit \"#{@post.title}\"" %>

<%= render 'shared/form', submit_button_text: "Update Post" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>
<div id="post_group">
  <%= render @posts %>
</div>
<%= render 'shared/pagination', link_type: :posts %>

app/views/posts/index.js.erb
$("#post_group").fadeOut(300, function() {
  $("#post_group").html("<%= escape_javascript( render @posts, formats: [:html] ) %>").fadeIn(300);
});

$("#paginate_group").replaceWith("<%= escape_javascript(render 'shared/pagination', link_type: :posts, formats: [:html] ) %>");

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post" %>

<%= render 'shared/form', submit_button_text: "Create Post" %>

app/views/posts/show.html.erb
<% if current_user == @post.creator || admin? %>
  <p class='pull-right'>
    [<%= link_to 'Edit Post', edit_post_path(@post) %>]
  </p>
<% end %>

<%= render @post.categories %>

<p class='lead'>
  <%= link_to @post.title, fix_url(@post.url) %>
  <hr/>
</p>

<div>
  <p><%= @post.description %></p>
  <p>
    <br>
    <span class='quiet'>Posted by: </span><%= link_to @post.creator.username, user_path(@post.creator) %>
    <small> - <%= format_full_time(@post.created_at) %></small>
  </p>
</div>
<hr/>

<% if logged_in? %>
  <% if @comment.errors.any? %>
    <div class='alert alert-error'>
      <strong>Please correct the following errors:</strong>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for [@post,  @comment] do |f| %>
    <%= f.label :body, "Leave a comment:" %> 
    <%= f.text_area :body, rows: 3, class: 'span4' %>
    <br/>
    <%= f.submit "Submit Comment", class: 'btn btn-primary' %>
  <% end %>
<% end %>

<br>
<p class='lead'>
  Comments:
  <hr/>
</p>

<div id="comment-section">
  <%= render @post.comments.limit(@comment_limit), profile_page: false %>
</div>

<div class="span9" id="load_comments">
  <% if @post.comments.size > @comment_limit %>
    <%= link_to "Load more comments...", post_path(@post, limit: (@limit_increase + 5)), class: "btn btn-primary", id: "load-more-btn", remote: true %>
  <% end %>
</div>
<br>
<br>

app/views/posts/show.js.erb
$("#comment-section").append("<%= escape_javascript(render @post.comments.offset(@limit_increase).limit(5), profile_page: false) %>");

$("#load-more-btn").replaceWith('<%= link_to "Load more comments...", post_path(@post, limit: (@limit_increase + 5)), class: "btn btn-primary", id: "load-more-btn", remote: true %>')

if (<%= @post.comments.size <= @comment_limit %>) {
  $("#load_comments").fadeOut(100);
}

app/views/posts/vote.js.erb
$("#post_<%= @post.slug %>_votes").fadeOut(200, function() {
  $("#post_<%= @post.slug %>_votes").hide().html("<%= @post.js_message %>").fadeIn(200, function () {
    $("#post_<%= @post.slug %>_votes").delay(1000).fadeOut(200, function () {      
      $("#post_<%= @post.slug %>_votes").hide().html("<%= @post.vote_total %> votes").fadeIn({duration: 200, queue: false});
    });
  });
});

$('#post_<%= @post.slug %>_arrow<%= @post.fade_out %>').fadeOut({duration: 200, queue: false});

$('#post_<%= @post.slug %>_arrow<%= @post.fade_in %>').removeClass('collapse').hide().delay(200).fadeIn(200);